# Generated by Django 4.1.7 on 2023-03-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='email',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
