# Generated by Django 4.1.7 on 2023-03-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contatos_email_alter_contatos_nome_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contatos',
            new_name='Contato',
        ),
    ]
