# Generated by Django 4.1.7 on 2023-03-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_rename_contatos_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='mostra',
            field=models.BooleanField(default=True),
        ),
    ]
